### ISSUE TITLE
小白引用这个项目是 python 提示出错， 具体如下贴图,如果大神有时间 可否帮忙看一下 

### ISSUE THREAD

**Issue by YountMan** [329703622/wechatpi#2]
![Uploading 123.png…]()

**Comment by YountMan** [comment]
956 ?        00:00:00 polkitd
  977 ?        00:00:00 gvfs-udisks2-vo
  979 ?        00:00:00 rtkit-daemon
  984 ?        00:00:00 udisksd
  996 ?        00:00:00 gvfs-mtp-volume
 1000 ?        00:00:00 gvfs-goa-volume
 1004 ?        00:00:00 gvfs-afc-volume
 1009 ?        00:00:00 gvfs-gphoto2-vo
 1018 ?        00:00:00 gvfsd-trash
 1026 ?        00:00:00 menu-cached
 1051 ?        00:00:00 sshd
 1056 ?        00:00:00 systemd
 1061 ?        00:00:00 (sd-pam)
 1064 ?        00:00:00 sftp-server
 1069 ?        00:00:00 sshd
 1076 pts/0    00:00:00 bash
 1101 pts/0    00:01:38 mjpg_streamer
 1130 ?        00:00:00 kworker/u8:2
 1131 ?        00:00:00 kworker/0:0
 1148 ?        00:00:00 kworker/1:0
 1151 pts/0    00:00:00 ps
root@raspberrypi:~# kill 1101
root@raspberrypi:~# clear
root@raspberrypi:~# sh start.sh
“正在加载摄像头驱动”
“正在启动主程序”
MJPG Streamer Version: svn rev:
 i: Using V4L2 device.: /devideo0
 i: Desired Resolution: 320 x 240
 i: Frames Per Second.: 10
 i: Format............: YUV
 i: JPEG Quality......: 80
ERROR opening V4L interface: Device or resource busy
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
Traceback (most recent call last):
  File "index.py", line 16, in <module>
    from yeelink import YeeLinkClient
ImportError: No module named yeelink
root@raspberrypi:~# nano index.py
root@raspberrypi:~# nano index.py
root@raspberrypi:~# sh start.sh
“正在加载摄像头驱动”
“正在启动主程序”
MJPG Streamer Version: svn rev:
 i: Using V4L2 device.: /devideo0
 i: Desired Resolution: 320 x 240
 i: Frames Per Second.: 10
 i: Format............: YUV
 i: JPEG Quality......: 80
 o: www-folder-path...: disabled
 o: HTTP TCP port.....: 8001
 o: username:password.: disabled
 o: commands..........: disabled
Traceback (most recent call last):
  File "index.py", line 18, in <module>
    from yeelink import *
ImportError: No module named yeelink
root@raspberrypi:~#

**Comment by YountMan** [comment]
root@raspberrypi:~# sh start.sh
“正在加载摄像头驱动”
“正在启动主程序”
MJPG Streamer Version: svn rev:
 i: Using V4L2 device.: /devideo0
 i: Desired Resolution: 320 x 240
 i: Frames Per Second.: 10
 i: Format............: YUV
 i: JPEG Quality......: 80
 o: www-folder-path...: disabled
 o: HTTP TCP port.....: 8001
 o: username:password.: disabled
 o: commands..........: disabled
Traceback (most recent call last):
  File "index.py", line 18, in <module>
    from yeelink import *
ImportError: No module named yeelink
root@raspberrypi:~#

**Comment by YountMan** [comment]
```
root@raspberrypi:~# sh start.sh
“正在加载摄像头驱动”
“正在启动主程序”
MJPG Streamer Version: svn rev:
 i: Using V4L2 device.: /devideo0
 i: Desired Resolution: 320 x 240
 i: Frames Per Second.: 10
 i: Format............: YUV
 i: JPEG Quality......: 80
ERROR opening V4L interface: Device or resource busy
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
Traceback (most recent call last):
  File "index.py", line 16, in <module>
    from yeelink import YeeLinkClient
ImportError: No module named yeelink
root@raspberrypi:~# nano index.py
root@raspberrypi:~# nano index.py
```

**Comment by mcdona1d** [comment]
没有把yeelink.py依赖放到跟index同一目录
